services:
  - type: redis
    name: supplier-server-redis
    plan: starter
    ipAllowList: []

  - type: web
    name: supplier-server-web
    env: node
    buildCommand: 'pnpm install'
    startCommand: 'npx tsx scripts/server.ts'
    autoDeploy: false
    envVars:
      - fromGroup: nodejs
      - key: REDIS_URL
        fromService:
          name: supplier-server-redis
          type: redis
          property: connectionString
      - key: SUPPLIER_SERVICE_TYPE
        value: monitor
      - key: WEB_UI_PASSWORD
        sync: false
      - key: NODE_VERSION
        value: 18.17.1

  - type: worker
    name: supplier-server-worker
    env: node
    buildCommand: 'pnpm install'
    startCommand: 'pnpm worker'
    autoDeploy: false
    envVars:
      - fromGroup: nodejs
      - key: REDIS_URL
        fromService:
          name: supplier-server-redis
          type: redis
          property: connectionString
      - key: SUPPLIER_STX_KEY
        sync: false
      - key: SUPPLIER_BTC_KEY
        sync: false
      - key: SUPPLIER_ID
        sync: false
      - key: SUPPLIER_SERVICE_TYPE
        value: worker
      - key: SUPPLIER_NETWORK
        sync: false
      - key: NODE_VERSION
        value: 18.17.1

envVarGroups:
  - name: nodejs
    envVars:
      - key: SUPPLIER_NETWORK
        sync: false
