name: Code checks
on: [push, workflow_dispatch]

jobs:
  code_checks:
    name: Code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7.25.1
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-dependencies
      - name: Typecheck
        run: pnpm typecheck
      - name: Lint
        run: pnpm lint
